/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.ionicframework.starter;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class raw {
        public static final int beep=0x7f040000;
        public static final int flashlight_turn_off_icon=0x7f040001;
        public static final int flashlight_turn_on_icon=0x7f040002;
        public static final int ic_btn_search=0x7f040003;
        public static final int poweredby2x=0x7f040004;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
    }
    public static final class xml {
        public static final int config=0x7f030000;
    }
}
